### ISSUE TITLE
[Bug]: emmet-core pymatgen pin

### ISSUE THREAD

**Issue by utf** [materialsproject/emmet#1052]
Is it necessary to pin `pymatgen==2024.4.13` for emmet-core? This is causing downstream issues in atomate2.

**Comment by tsmathis** [comment]
The pin has been in place due to upstream conflicts for emmet as well, see here #1020

Re-checking now though it seems like we should be good after this (https://github.com/MDAnalysis/solvation-analysis/issues/106) is resolved

**Comment by utf** [comment]
Oops, I missed that. Closing as a duplicate. Thanks.
