### ISSUE TITLE
[Bug]: Hitting Tab or Enter to pop-up suggestion does nothing if HTML tag started with less-than character (<)

### ISSUE THREAD

**Issue by davehodls** [materialsproject/emmet#1081]
### Code snippet

```python
<ol
```

### What happened?

Whenever I make an HTML tag using the old-fashioned way starting with a less-than character (`<`), then Emmet pops up a suggestion to complete the tag with, hitting Tab or Enter just closes the suggestion.

When I start typing a tag name without the `<`, Emmet pops up a potential suggestion, and then hitting Tab or Enter writes the whole tag (including any expected end tag).

There's one of two problems with this:
1. Emmet should be completing the tag as suggested for a tag starting with `<` like it does with a tag name that wasn't typed starting with `<`, or
2. Emmet should not offer a suggestion to tags started with `<`, because it won't complete it.

You gotta pick one or the other. Having inconsistent Tab/Enter behavior for the same suggestion pop-up to different ways of starting a tag is overly-punishing to a dev not doing it some particular way. Either complete the tag both ways, or complete it only the way you want us to start it.

Frankly I see no problem with solution #1, just completing the tag both ways. **If it's gonna make the suggestion both ways, it should finish them the same way.**

Note about this form: the 'Submit new issue' button is disabled without any indication as to why. When I go to Inspect and remove the 'disabled' attribute, then click the button, it finally shows me what's wrong; the Version field is not filled out, even though it already looks like it is because the placeholder text color looks the same as the surrounding text. There's no need to disable the Submit button if it's already going to run validation and tell me what's wrong. Please trust your coders to do your forms right.

### Version

v1.92.2

### Which OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by tsmathis** [comment]
Hi @davehodls, just checking, are you in the right 'emmet'? This is a repository related to computational materials science database tooling. 

Is this meant for the web dev toolkit [emmet](https://github.com/emmetio/emmet)?
