### ISSUE TITLE
Rotate structure to standard convention

### ISSUE THREAD

**Issue by shyamd** [materialsproject/emmet#111]
We should rotate the crystal to the "standard" convention in the website builder. Spglib already has this but we may need to add it to `SpaceGroupAnalyzer`

https://discuss.matsci.org/t/space-group-pbnm-pnma-62-bug-or-not/3301

**Comment by mkhorton** [comment]
There’s a decent argument for putting it in a conventional setting by default too (even if “primitive conventional“).

**Comment by shyamd** [comment]
Fixed, but can't find the PR so unable to cross-ref. Gotta clean these up more regularly so this doesn't happen again.
