### ISSUE TITLE
`pydantic.config.Extra` is deprecated, use literal values instead (e.g. `extra='allow'`)

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/emmet#1119]
Got the following deprecation warning from `emmet/core/vasp/calculation`:

```
venv/lib/python3.12/site-packages/emmet/core/vasp/calculation.py:304
  /Users/yang/developer/api/venv/lib/python3.12/site-packages/emmet/core/vasp/calculation.py:304: PydanticDeprecatedSince20: `pydantic.config.Extra` is deprecated, use literal values instead (e.g. `extra='allow'`). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
    class ElectronicStep(BaseModel, extra=Extra.allow):  # type: ignore

venv/lib/python3.12/site-packages/emmet/core/vasp/calculation.py:328
  /Users/yang/developer/api/venv/lib/python3.12/site-packages/emmet/core/vasp/calculation.py:328: PydanticDeprecatedSince20: `pydantic.config.Extra` is deprecated, use literal values instead (e.g. `extra='allow'`). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
    class IonicStep(BaseModel, extra=Extra.allow):  # type: ignore
```

https://github.com/materialsproject/emmet/blob/8ece13eff9eb33d2733f4415aafa1d2ed66703b9/emmet-core/emmet/core/vasp/calculation.py#L328

https://github.com/materialsproject/emmet/blob/8ece13eff9eb33d2733f4415aafa1d2ed66703b9/emmet-core/emmet/core/vasp/calculation.py#L304

Not sure if [the following from official documentation is related](https://docs.pydantic.dev/2.9/migration/#changes-to-dataclasses):

> Pydantic no longer supports extra='allow' for Pydantic dataclasses, where extra fields passed to the initializer would be stored as extra attributes on the dataclass. extra='ignore' is still supported for the purpose of ignoring unexpected fields while parsing data, they just won't be stored on the instance.

**Comment by tsmathis** [comment]
Thanks for point this out @DanielYang59

**Comment by DanielYang59** [comment]
No problem! Thanks for fixing
