### ISSUE TITLE
SurfacePropertiesBuilder

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/emmet#23]
Database builder for surface properties. Will combine raw data from oriented unit cell calculations and slab calculations of different facets to generate a Wulff shape and obtained related properties such as the weighted_surface_energy, weighted_work_function, shape_factor, etc.

**Comment by dwinston** [comment]
Hi @richardtran415, this doesn't seem to be a proper issue as much as a heads up that you may open up a WIP PR soon for such a builder. so I'm closing.
