### ISSUE TITLE
Elastic builder

### ISSUE THREAD

**Issue by mjwen** [materialsproject/emmet#245]
I've started working on the elastic builder in the `updates` branch and made some fixes to make it work with latest `maggma`. This is still WIP, but I want to check what is the plan for the elastic builder; seems it is not in the main branch. Do we need to migrate it to main from updates but haven't done it yet, or is there something else need to happen?

**Comment by mkhorton** [comment]
I believe there is no elastic builder on the `main` branch and it needs to be written/migrated, @shyamd correct me if I'm wrong. I think we've been treating the elastic collection as a static collection while you've been figuring out these issues.
