### ISSUE TITLE
A generalized warning generator for task documents?

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/emmet#26]
Is there a class or function in emmet that can take any kind of taskdoc or maybe just a vasp calculation task doc and analyze it for common types of anomalies that might occur in a calculation e.g. too much relaxation.

Or maybe there should be a separate folder in the emmet/vasp directory called warnings where there is a generic_warnings.py module for general warnings that can be applied to most calculations and a elastic.py, surface.py, diffraction.py modules for more specific warnings related to each dataset?

**Comment by dwinston** [comment]
There is no such class or function yet, but this seems like a fine idea. Such a sentinel could be called by a builder before/as it processes items.

**Comment by shyamd** [comment]
Shouldn't whomever is writing the builder know what to warn on? I'd rather the builders write their own top level "warnings" key as either a dict or list. We can standardize on format, but don't think we need a separate builder. That creates too much abstraction.

**Comment by dwinston** [comment]
Sure. I agree that it may be too early to know what these generic warnings are apart from deducing them from warnings commonly written by a number of builders. When we see such repetition, we can propose abstraction. Closing this.
