### ISSUE TITLE
KeyError when running lu_field with a store already containing data

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/emmet#45]
I'm currently trying to debug my SurfaceBuilder right now, but I seem to be running into an issue every time I try using it to post-process and insert data into my store. When initializing the SurfaceBuilder class, I insert two stores, one containing raw data from vasp (called materials) and the other for holding post processed data (surfprops_store). I have a fairly typical get_items() class method in the SurfaceBuilder and if the surfprops_store is empty (there is no data inserted yet) and I run my builder, it works just fine. However, if data already exists, the get_items() method will run into an issue with the following line of code:

f = self.materials.lu_filter(self.surfprops_store)

which causes a KeyError:
"""
/maggma/maggma/stores.py in lu_filter(self, targets)
     95             targets = [targets]
     96 
---> 97         lu_list = [t.last_updated for t in targets]
     98         return {self.lu_field: {"$gt": self.lu_func[1](max(lu_list))}}
     99 

/maggma/maggma/stores.py in <listcomp>(.0)
     95             targets = [targets]
     96 
---> 97         lu_list = [t.last_updated for t in targets]
     98         return {self.lu_field: {"$gt": self.lu_func[1](max(lu_list))}}
     99 

/maggma/maggma/stores.py in last_updated(self)
     79             [(self.lu_field, pymongo.DESCENDING)]).limit(1), None)
     80         # Handle when collection has docs but `NoneType` lu_field.
---> 81         return (self.lu_func[0](doc[self.lu_field]) if (doc and doc[self.lu_field])
     82                 else datetime.min)
     83 

KeyError: 'last_updated'
"""

I'm assuming the way lu_fillter() works is that it reads through the store with the raw data (materials) and filters out any data that already exists in the post processed store. But I can't seem to figure out why this would cause an error if data already exists in the post-processed store.

**Comment by montoyjh** [comment]
Hey Richard, the lu_filter works by finding the maximum date of the target store for all values correspoding to the lu_field (by default this is "last_updated") by default and only getting documents from the source store which have lu_fields which are greater than that, this ensures that only documents which have been added to the source store after the latest entry in the target store are used in the build.  I suspect that the issue is that surfprops_store might not have a last updated field?

**Comment by shyamd** [comment]
thanks for the fix @dwinston  #26
