### ISSUE TITLE
Merging schemas from atomate2 

### ISSUE THREAD

**Issue by utf** [materialsproject/emmet#517]
Since atomate2 is now fairly stable, I wanted to start a discussion about the best route to merging the schemas in atomate2 with those in emmet. There are a few potential issues and I'm not sure how best to tackle them.

1. The VASP task documents from atomate1 and atomate2 are slightly different. We added some new fields in atomate2 and potentially changed some existing fields too. This seems like a major issue? I can try minimising the changes so that only new fields are added and no existing fields are changed. Would this be OK?
2. In atomate2, many of the task documents include logic for initialising them from raw calculation files. E.g., vasprun.xml & OUTCAR in the case of VASP. Where should this logic live? If this isn't suitable for emmet, one workaround would be to subclass the emmet schemas in atomate2 and only add these additional loading functions. E.g., `from_vasp_files` for the VASP task document.

What do you think @mkhorton @munrojm @jmmshn @rkingsbury

**Comment by jmmshn** [comment]
I think the construction from raw data functionality should live in emmet, I'm pretty sure there are examples of that in emmet already.  Having at least the important document models in one place will be super helpful in the future.

**Comment by mkhorton** [comment]
I'm very glad you're bringing this again @utf -- I think this is very important.

I agree with @jmmshn that, ideally, `emmet-core` should contain these document models so that we can re-use them, with perhaps only atomate2-specific ones living inside atomate2. I think it'd be appropriate to add you (@utf) as a maintainer to this if we wanted to go this route, since I wouldn't want to introduce too much development friction with having them located in a different place.

For the specific questions:

1. It's a major issue in the sense that it's often unfeasible (or in some cases, impossible) to re-parse the existing Materials Project calculations. If there are simple changes like field name changes, etc., then a database migration script would go a long way, and would presumably be very fast if we write it in pure Mongo.
2.

**Comment by munrojm** [comment]
Don't much much to say that hasn't already been said.

I agree with both @jmmshn and @mkhorton that the non-atomate2 specific models should live in `emmet-core` with all of their associated construction methods. I was also going to suggest that you (@utf) should be added as a maintainer to `emmet` to reduce friction. 

Additionally, I agree that the only real issue with the task model lies with altering existing fields due to an inability to re-parse everything. Do you feel strongly about any of the field changes in particular @utf? Full disclosure that I haven't had a chance to look at the updated model.

**Comment by utf** [comment]
Great, I think it should be possible to massage the atomate2 documents in line with emmet.

> I think attached to the document model, e.g. from_vasp_files() as a method on the document model, makes complete sense. I think this would be fine in emmet. Was there a specific reason you thought this wouldn't be suitable?

One worry I had is about dependency bloat. For example, in the new phonon workflow. The Phonon task document has a constructor that can take a list of displacement structure and energies and run phonopy.  This is part of the task document itself, and the plan is that the builder could even just call this function once the displacements and energies care collected. However, this will introduce the phonopy dependency.

If this isn't an issue then that's great!

**Comment by utf** [comment]
Having a look at the VASP task document in emmet in more detail, it seems like quite a minimal document now. I remember some time ago it being much more detailed, as I used the emmet doc as the basis for atomate2. Is there a reason much of detail has been removed? E.g., there is no schema for calcs_reversed?

**Comment by munrojm** [comment]
> Having a look at the VASP task document in emmet in more detail, it seems like quite a minimal document now. I remember some time ago it being much more detailed, as I used the emmet doc as the basis for atomate2. Is there a reason much of detail has been removed? E.g., there is no schema for calcs_reversed?

The main task doc model is this one https://github.com/materialsproject/emmet/blob/main/emmet-core/emmet/core/tasks.py

The other one is used strictly in the validation builder. Not sure why there are two, but I have been meaning to consolidate for a while now.

**Comment by mkhorton** [comment]
Just to double check, are you looking at the correct `TaskDoc`? https://github.com/materialsproject/emmet/blob/d77b80d51669edcbbfb8de2180db087afacfc321/emmet-core/emmet/core/tasks.py#L142

I believe another `TaskDocument` was added in the hopes this could provide a base model that task docs for multiple codes could inherit from, but this is more aspirational right now.

**Comment by mkhorton** [comment]
> However, this will introduce the phonopy dependency.

I share the concern if it's only inside that specific method, but we could make it optional and import from within the method?

As a rule, if we keep the non-optional dependencies as only the ones strictly required to instantiate a document model (with arbitrary data) I think we'll be ok.

**Comment by utf** [comment]
Right, I was definitely looking at the wrong one. Thanks for clarifying.

Can I ask why this is not in the `vasp` module when it looks fairly specific to VASP? E.g., referencing pseudo potentials etc?

I am very in favour developing a base task doc that can support multiple DFT codes. This is something we are starting to explore with @gpetretto and @davidwaroquiers, with their addition of abinit to atomate2.

**Comment by utf** [comment]
There is also one other issue I forgot. In atomate1/MP you use `task_id`, whereas in atomate2 we use `uuid`. This mainly manifests when storing metadata, for example, in our ElasticDoc, we store the uuids of the distortion calculations. Am I ok to include this field since it is really an extra field that the existing documents will ignore?

**Comment by munrojm** [comment]
> Right, I was definitely looking at the wrong one. Thanks for clarifying.
> 
> Can I ask why this is not in the `vasp` module when it looks fairly specific to VASP? E.g., referencing pseudo potentials etc?
>

No good reason. The modules in core need to be re-organized. 

> There is also one other issue I forgot. In atomate1/MP you use task_id, whereas in atomate2 we use uuid. This mainly manifests when storing metadata, for example, in our ElasticDoc, we store the uuids of the distortion calculations. Am I ok to include this field since it is really an extra field that the existing documents will ignore?

Yes, that should be totally fine.

**Comment by rkingsbury** [comment]
Thanks for raising the question @utf ; like @munrojm I don't have much to add that hasn't already been covered. I'll make one comment regarding dependencies:

> One worry I had is about dependency bloat. For example, in the new phonon workflow. The Phonon task document has a constructor (e.g., something like PhononDocument.from_structures_and_energies) that can take a list of displacement structure and energies and run phonopy. This is part of the task document itself, and the plan is that the builder could even just call this function once the displacements and energies care collected. However, this will introduce the phonopy dependency.

For this specific reason, long-term I feel there could be an argument for housing the _code-specific_ `Document` (e.g., the contents of `emmet/core/vasp`) elsewhere than `emmet` - e.g. in an `io` module in pymatgen or an IO addon package. All the downstream document models (that live in `/emmet/core/`) should definitely stay in `emmet`.

Making you a maintainer and having a robust system in place for optional dependency handling as @mkhorton proposed is another way to address this. Functionally, the end state that I hope to see is that it's possible to install `emmet` and `atomate2` without installing a bunch of VASP-centric dependencies if I am only interested in using them with Q-Chem, for example, or some other code.

**Comment by mkhorton** [comment]
> For this specific reason, long-term I feel there could be an argument for housing the code-specific Document (e.g., the contents of emmet/core/vasp) elsewhere than emmet - e.g. in an io module in pymatgen or an IO addon package. All the downstream document models (that live in /emmet/core/) should definitely stay in emmet.

For practical purposes, I'm not sure this helps much, because then we have document models defined in multiple places and maintenance burden increases.

My hope is that it should be very rare to have to introduce a dependency just to introduce a new document model, because most of the data types defined by the document model are either going to be native data types, or perhaps pymatgen core classes, but rarely anything else.

**Comment by jmmshn** [comment]
Just linking related discussion:
https://github.com/materialsproject/atomate2/issues/150

**Comment by jmmshn** [comment]
> For this specific reason, long-term I feel there could be an argument for housing the code-specific Document (e.g., the contents of emmet/core/vasp) elsewhere than emmet - e.g. in an io module in pymatgen or an IO addon package. All the downstream document models (that live in /emmet/core/) should definitely stay in emmet.

I think the document model stuff is mostly not a concern outside of seasoned MP ppl so having it maintained in one place makes sense.
I think having all this stuff living one layer removed from the end users who will mostly use atomate/pymatgen is OK.  especially since they can already develop workflows without thinking too much about document models outside of "oh I can access this from TaskDocument".

For the io stuff, we should just strongly encourage people to use `dataclasses` which will solve all the worst parts of porting over objects from pymatgen into emmet.  And it helps you avoid terrible things like custom `as_dict` / `from_dict`.

**Comment by utf** [comment]
Ok, it seems decided that relevant models will live in emmet and that we will make use of optional dependencies. Thanks for the discussion all!

I think there will be a little confusion about when a model should graduate from atomate2 to emmet. E.g., we are adding CP2K task documents. MP doesn't have any CP2K data yet, so it might not make sense to have the task documents in emmet, but at some point it could do, at which point the models will have to be transferred. But we can handle this on a case-by-case basis.

When I get some free time, I will start the merge. At the moment I'm only planning on merging the VASP documents and the elastic documents.

**Comment by mkhorton** [comment]
> I think there will be a little confusion about when a model should graduate from atomate2 to emmet. E.g., we are adding CP2K task documents. MP doesn't have any CP2K data yet,

Ok, I think maybe these are the two points left to clarify:

1. The purpose of `emmet-core`; is it to power MP, or a general host of document models for the community? To date, it's really been the former, to make it work well as the latter we probably need to (at least) make sure it has appropriate documentation and contribution guidelines.
2. What guidance to give people about where to put their document models. Perhaps, in the atomate2 docs, we can recommend checking `emmet-core` to see if an appropriate document model already exists (e.g., if a new workflow is predicting, say, elastic tensors but via an alternative method), and if not we could advise people to include them in atomate2, and leave it to the project maintainers to upstream the document models at a later date?

The other aspect of this discussion is making sure people use the correct base class, e.g. the TaskDocument for a new task document, or PropertyDoc for a new type of property, and perhaps we could use separate discussions for whatever modifications to these base classes may be necessary.

**Comment by rkingsbury** [comment]
> 1. The purpose of `emmet-core`; is it to power MP, or a general host of document models for the community?
> To  date, it's really been the former, to make it work well as the latter we probably need to (at least) make sure it has 
> appropriate documentation and contribution guidelines.

Agree this is quite important to clarify. I don't feel the 2nd option is very realistic in the long-term - there are just too many codes and potential models that people might want to use. I think it's valuable as a concrete illustration of MP's paradigm, and it makes sense for doc models for whatever codes MP uses to live there.


> 2. What guidance to give people about where to put their document models. Perhaps, in the atomate2 docs, we can recommend checking `emmet-core` to see if an appropriate document model already exists (e.g., if a new workflow is predicting, say, elastic tensors but via an alternative method), and if not we could advise people to include them in atomate2, and leave it to the project maintainers to upstream the document models at a later date?

I like this proposal.

**Comment by utf** [comment]
This is done now!
