### ISSUE TITLE
ChemEnv integration

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/emmet#595]
As mentioned by mail, I would like to provide the ChemEnv data, @munrojm.

I am currently testing several options:
- full run based on current implementation (12 hours on 24 cores for me, our system has a lot of memory available)
- coordination environments only for structures which have oxidation states  (5 hours on 24 cores)
- coordination environments only for structures which have less than or equal to 100 inequivalent sites in the structure to reduce the run times 
- combination of both options

I will add run times and provide potential implementations in the form of a pull request in a next step. We should potentially test the fastest option first and then see if this is doable on your systems and potentially extend the number of compounds complexity step by step.

**Comment by JaGeo** [comment]
I think I will just make a pull request for the option where we only do the analysis when oxidation states are available. I will uncomment the other code for now. It runs at least twice as fast and should also be easier to understand for users if only one type of ChemEnv analysis is used.

**Comment by munrojm** [comment]
@JaGeo, just pinging you here to let you know I am debugging some builder pipeline issues which is delaying me on getting the `chemenv` stage up and running. This should be done soon, and I will update this thread.

**Comment by JaGeo** [comment]
@munrojm Thanks for the update! 🙂

**Comment by munrojm** [comment]
@JaGeo, the builder runs well! I am able to get it completed in ~5hrs within our build pipelines. The data should be incorporated into the DB and available through the API next release.

**Comment by JaGeo** [comment]
@munrojm  Awesome! 🥳 Thank you so much!

**Comment by JaGeo** [comment]
@munrojm If there is more documentation needed to make this available, just let me know. I am happy to help with this as well.

**Comment by munrojm** [comment]
@JaGeo, I appreciate the offer. Apologies again for the delay on this. This is essentially ready to go on the API side. Our initial intent was to wait to bundle this with some other data in the next DB release, but that kept getting pushed back for a number of reasons. Currently, I am working to fix up thermo data related issues. We intend to deploy again soon with to accommodate the changes. What I will do is include the ChemEnv data in that deployment so it is available next week.

**Comment by JaGeo** [comment]
Great, thank you!

**Comment by JaGeo** [comment]
I do have an additional question: would it be in principle possible to get a DOI for such a dataset (the whole one)?

**Comment by munrojm** [comment]
@JaGeo The DOIs we get from OSTI need to be matched to a landing page. Dataset contributions to core and not MPContribs don't have that, and thus we can't assign DOIs for them. @tschaume can weigh in on this in case I am getting something wrong. 

On another note, do you have any particular things you would like to have included as filters on the chemenv data within the API? `chemenv_iucr` for example?

**Comment by JaGeo** [comment]
I think a filter on the environment names would be good: `chemenv_iucr`, `chemenv_name` and maybe also a filter on the "continous symmetry measure" to exclude very distorted environments,, for example.

**Comment by munrojm** [comment]
@JaGeo, feel free to try pulling the data with the latest MPRester and let me know what other changes you would like to make. We are going to be working on website integration soon.

**Comment by JaGeo** [comment]
Thank you, @munrojm ! I will try to test it during this week!

**Comment by JaGeo** [comment]
@munrojm, I was too curious and I added some suggestions here: https://github.com/materialsproject/api/pull/771
