### ISSUE TITLE
similar materials available for legacy but not next-gen

### ISSUE THREAD

**Issue by tschaume** [materialsproject/emmet#620]
@munrojm The following materials are examples for cases where similar materials have been calculated for the legacy site but not nextgen.

- [La5Mn5O16](https://materialsproject.org/materials/mp-531717) 
- [CaWF6](https://materialsproject.org/materials/mp-1395540)
- [MgWF6](https://materialsproject.org/materials/mp-1407403)
- [ZnWF6](https://materialsproject.org/materials/mp-1400616)
- [MgSnF6](https://materialsproject.org/materials/mp-1397451)

It looks like the similarity documents for the respective mp-ids are not found, e.g. https://api.materialsproject.org/similarity/mp-1395540/?_all_fields=True&_limit=1

FYI @kristinpersson @mattmcdermott

**Comment by munrojm** [comment]
No problem, I can fix this. Just need to update the MPIDs in the static collection.
