### ISSUE TITLE
Support for numpy 1.24

### ISSUE THREAD

**Issue by jan-janssen** [materialsproject/emmet#624]
Can you add support for numpy version 1.24?

**Comment by ml-evs** [comment]
I'd really appreciate this too, I'm being sent into circular dep hell trying to support emmet_core/pymatgen/pandas and various subdeps across several projects.

**Comment by ml-evs** [comment]
In case anyone else stumbles upon this, here's how the `numpy<1.24` pin in this repo manifested itself:

1. Project already has numpy 1.24 as the tested version in CI
2. Automatic pinned deps update for new pymatgen version arrives
3. Many attempts to install older versions of emmet-core until it hits the one before this pin (0.39 something)
4. Failure with error message regarding pybtex and 2to3 conversion which crashes pip (old version)
   

<summary>Pip error message
<details>

```
Collecting pybtex
      Downloading pybtex-0.23.0-py2.py3-none-any.whl (279 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.9/279.9 kB 73.4 MB/s eta 0:00:00
  Downloading pybtex-0.22.2-py2.py3-none-any.whl (279 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.3/279.3 kB 76.2 MB/s eta 0:00:00
  Downloading pybtex-0.22.1-py2.py3-none-any.whl (279 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.3/279.3 kB 60.9 MB/s eta 0:00:00
  Downloading pybtex-0.22.0-py2.py3-none-any.whl (279 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.3/279.3 kB 78.1 MB/s eta 0:00:00
  Downloading pybtex-0.21.tar.gz (364 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.8/364.8 kB 58.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      /opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'use_2to3_fixers'
        warnings.warn(msg)
      error in pybtex setup command: use_2to3 is invalid.
      [end of output]
```

</details>
</summary>

**Comment by munrojm** [comment]
This was a temporary fix for an issue that originated in pymatgen. I am unpinning it now that a newer version is released.

**Comment by ml-evs** [comment]
Awesome, thanks! Any chance of a cheeky patch release to PyPI?

**Comment by munrojm** [comment]
Yup! Will patch release once our dependency upgrade action finishes. Should
be 15 min or so.

- Jason

**Comment by ml-evs** [comment]
Much obliged!
