### ISSUE TITLE
Returned docs too large for common API queries (third-order elasticity)

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/emmet#76]
https://github.com/materialsproject/emmet/blob/36a3cbc7c627aa53af38b06c31992875e4827d04/emmet/vasp/elastic.py#L339

e.g. check out the doc returned for "mp-13", "elasticity" -- could result in a non-negligible hit on API performance, a rough measurement seems to show that this document for mp-13 alone is about 2.5 MB.

(Issue raised in response to an email from SP)

**Comment by mkhorton** [comment]
Specifically seems to be the `elasticity.third_order.calculations` key.

**Comment by JosephMontoya-TRI** [comment]
Also a regression in warnings, which I suspect is happening during aggregation.  Will check today.

**Comment by shyamd** [comment]
I'm going to close this as it pertains more to the API and not this.
