### ISSUE TITLE
PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings`

### ISSUE THREAD

**Issue by janosh** [materialsproject/emmet#768]
[pymatgen CI](https://github.com/materialsproject/pymatgen/actions/runs/5432376407/jobs/9879373984?pr=3122) is failing with:

> E   pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package.
> See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.

Came up in https://github.com/materialsproject/pymatgen/pull/3122.

**Comment by peikai** [comment]
Encountering the same issue. 

> pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package.
> See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.

Besides, `PyObject` class (used in emmet/core/settings.py) has been deprecated from the pydantic v2.

**Comment by janosh** [comment]
See https://github.com/materialsproject/pymatgen/pull/3122/commits/1e9025428720db7e40cf532a1ff011ba50b11dfa for tmp fix

**Comment by peikai** [comment]
Thanks!

**Comment by munrojm** [comment]
I have just added `pydantic < 2.0` to the `emmet-core` dependencies to address this.

**Comment by janosh** [comment]
Thanks @munrojm.

Other MP repos might make the transition to `pydantic` v2 soonish (how about `atomate2` @utf?). Might require some coordination to minimize the time of clashing deps.

**Comment by arosen93** [comment]
I am strongly in favor of this! 😄

**Comment by mkhorton** [comment]
Agreed. Also linking the `jobflow` dependabot:

https://github.com/materialsproject/jobflow/pull/370

It would be good to have a strategy. I'd like to migrate myself, although I've been using another third-party library recently that's also pinned on `pydantic<2.0.0` so anticipating a little pain.

**Comment by mkhorton** [comment]
They are offering a `bump-pydantic` tool which might help https://docs.pydantic.dev/2.0/migration/#code-transformation-tool

**Comment by Andrew-S-Rosen** [comment]
@munrojm looks like this can be closed?
