### ISSUE TITLE
Issue with `run_type` function

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/emmet#781]
https://github.com/materialsproject/emmet/blob/c4580e2a220d2148ff3543f18c3b2ab3281491b0/emmet-core/emmet/core/vasp/calc_types/utils.py#L13

@munrojm According to @esoteric-ephemera , if you set both the METAGGA tag and the GGA tag in the INCAR, the METAGGA tag takes precedence. Hence, the current `run_type` function may incorrectly mark a METAGGA run as a GGA run.

I think all that would need to be fixed is to change the order in which you check these? Unsure. Need input from @esoteric-ephemera

**Comment by matthewkuner** [comment]
Honestly, this probably only matters for external calcs tho.

**Comment by esoteric-ephemera** [comment]
Correct, you would just need to pop GGA from the dict if METAGGA is also in the dict. I think this ability to use both GGA and METAGGA tags is being removed in a future VASP 6
