### ISSUE TITLE
[conda package] missing dependence on `custodian`

### ISSUE THREAD

**Issue by mbruns91** [materialsproject/emmet#890]
Our package [`pyiron_atomistics`](https://github.com/pyiron/pyiron_atomistics) depends indirectly on `emmet-core` via `mp-api`. When `emmet-core` is installed from conda-forge, there seems to be a missing dependency of `emmet-core` on `custodian`, what causes our CI runs to fail with error messages like `from custodian.vasp.jobs import VaspJob; ModuleNotFoundError: No module named 'custodian'`.

As you can see from [this PR](https://github.com/pyiron/pyiron_atomistics/pull/1210), this can be fixed by adding `custodian` to `setup.py` and/or `environment.yml`. However, it may be a cleaner solution if you may add `custodian` to `emmet-core`'s dependencies in the relevant places.

I already opened a PR for this on [`emmet-core-feedstock`](https://github.com/conda-forge/emmet-core-feedstock/pull/149).

**Comment by munrojm** [comment]
This should be fixed as of the latest version of `emmet-core`.

**Comment by Andrew-S-Rosen** [comment]
@munrojm looks like this can be closed?
