### ISSUE TITLE
Thoughts on having StructureNL instead of Structure in canonical materials structure field?

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/emmet#97]
Could contain both the material id and the blessed task id for provenance.

**Comment by shyamd** [comment]
`StructureNL` is a bad container. There's a lot of complicated logic and moving things around between the raw data object and the python object. For instance, as a data object, it's a pymatgen structure + extra fields, but as a python object it doesn't wrap `Structure` directly but instead requires you to access the `structure` attribute. Raw fields in the data object get remapped to `about` in the python object. `remarks` has a wonky 140 character limit, but the other fields don't, etc.  I'd recommend going the other way and removing it wherever possible.

**Comment by mkhorton** [comment]
I forgot about this issue :) 

Yeah, I agree with `StructureNL`, but I think a Structure with provenance is a good idea. Let's leave this issue sit for a bit.
